locators={

    "xpath":{
# wadhwani_faculty xpaths

        "enter_username": "//*[@name='email']",
        "enter_password": "//*[@name='password']",
        "next_btn": "//*[text()='NEXT']",
        "sign_in_btn": "//*[text()='SIGN IN']",
        "click_on_course_header": "//*[@id='mysubs-menu']/a|//*[@id='faculty_courses']",
        "click_on_preview_course":"(//*[@class='start_course_button preview'])[1]",
        "assert_preview_course":"//*[contains(text(),'Course Details')]",
        "click_on_video_intro": "(//*[@title='Video: Introduction'])[1]",
        "click_on_video": "(//*[@class='single_content_image_play'])[2]",
        "assert_video_play": "//*[@class='videoview-video-title']",
        "click_on_toggle": "//*[@class='arrow-down notific-generic profile_toggle_down']| //*[@class='dropdown-toggle settings_caret']",
        "click_on_logout": "//*[contains(text(),'Logout')]",
        "click_on_next_button": "//*[@class='grey-button section_next']",
        "click_on_course_new_batch": "(//*[@class='course_create_batch'])",
        "click_on_create_new_batch": "(//*[@class='create_new_batch'])",
        "click_on_copy_batch":"(//*[@class='copy_batch_details'])",   # 1 to 3 index
        "click_on_copy_batch_2":"(//*[@class='copy_batch_details'])[2]",
        "expand_second_course_1":"(//*[@class='tag_view_list_wrapper'])[1]",
        "expand_second_course_2":"(//*[@class='tag_view_list_wrapper'])[2]",
        "selct_batch_for_copy":"//div[@class='batch_students ng-binding ng-scope']",
        "click_on_submit_btn":"//*[@class='submit_button md-button md-ink-ripple active_submit_button']",
        "search_copy_batch_name":"//*[@id='input_3']",
        "number_of_student":"//*[@name='numberOfStudent']",
        "click_on_date_picker":"//*[@class='md-datepicker-triangle-button md-icon-button md-button']",
        #"click_on_date_picker":"//*[@class='md-datepicker-input md-input']",
        "select_date":"//*[@class='md-calendar-date md-calendar-date-today md-focus']",
        "create_batch":"//*[@class='create_button md-button ng-scope md-ink-ripple']",
        "assert_create_batch":"//*[text()='Batch Details']",
        "click_on_dashboard":"//*[@id='home']/a|//*[@id='faculty_dashboard']",
        "click_on_start_btn":"(//*[contains(text(),'START')])[2]",
        "click_on_start_lw_33":"(//*[contains(text(),'START')])[last()-1]",
        "click_on_resume_btn":"(//*[contains(text(),'RESUME')])[2]",
        "click_on_teaching_mode_btn":"(//*[@class='ui-button ui-corner-all ui-widget'])[1]",
        "click_on_preparation_mode_btn":"(//*[@class='ui-button ui-corner-all ui-widget'])[2]",
        "assert_teaching_mode":"//*[@class='personal_class active']",
        "next_button_for_green_tick":"//*[@class='grey-button section_next']",
        "click_on_chapter_title":"//*[@class='chapter_title']",
        "click_on_lesson":"(//*[@class='chapter-title'])[2]",
        "click_on_resumen":"(//*[@class='left-topic-title'])[3]",
        "click_on_resumen_last":"((//*[contains(text(),'Orientation Program in Entrepreneurship (WFNEN 100)')])/../following-sibling::div[2])[1]//a/div",
        "assert_title_resumen":"(//*[@id='section_wrapper_id_406126'])[1]",
        "full_screen":"//*[@class='show_full_pdf content_is_fullscreen']",
        "recent_activities":"(//*[text()='Recent Activities'])[1]",
        "click_on_manage_batches":"//*[text()='MANAGE BATCHES']|//*[text()='Manage Batches']",
        "click_on_close_batches":"//*[@id='closeBatchAction']",
        "click_on_yes_btn":"//*[text()='Yes']",
        "course_tab": "//a[text()='Courses']",
        "create_Batch": "//a[text()='CREATE BATCH']",
        "copy_batch_ass": "//h1[text()='Copy batch']",
        "Copy_Batch_Tab": "//a[@class='copy_batch_details']",
        "Edit_batch": "(//i[@aria-hidden='true'])[4]",
        "edit_manage_std_tab": "//span[text()='EDIT']",
        "edit_manage_std_tf":"(//input[@name='batchName'])[1]",

        "start_rating":"(//*[@id='dialogContent_24']/div/form/md-dialog-content/div[2]//li)[5]",
        'star_rating_btn':'(//*[@id="dialogContent_0"]/div/form/md-dialog-content/h3/..//ul[@class="rating"]/li)[5]',
        "enter_comment_btn_1":"//*[@id='input_25']",
        "enter_comment_2":"//*[@id='input_1']",
        "submit_rating_btn":"//button[@class='yes_button md-button ng-scope md-ink-ripple']",
        "assert_zero_batch":"//*[text()=' (0) ']",
        "ecell_button":"//*[@id='ecell']/a|//*[@id='student_ecell']",
        "setup_ecell_btn":"//*[@class='md-button md-ink-ripple']",
        "select_student":"//*[@id='fl-input-0'']",
        "select_any_one":"//*[@class='item-metadata ng-binding']",
        "nominate_btn":"//*[@class='submit_button md-button ng-scope md-ink-ripple']",
        "assert_congrats":"//*[text()='Congratulations!']",
        "student_ecell":"//*[@id='student_ecell']",
        "student_setup_ecell":"//*[@class='md-button md-ink-ripple']",
        "enter_ecell_name":"//*[@id='input_1']",
        "enter_web_name":"//*[@id='input_2']",
        "enter_description_btn":"//*[@id='input_6]",
        "ecell_save_button":"//*[@class='md-button ng-scope md-ink-ripple']",
        "activate_btn":"//*[text()='ACTIVATE NOW']",
        "stu_toggle_btn":"//*[@class='dropdown-toggle settings_caret']",
        "stu_logout_btn":"//*[text()='Logout']",
        "add_now_activity":"//*[text()='ADD NOW']",
        "click_on_add_btn":"(//*[text()='ADD'])[1]",
        "schedule_btn":"//*[@class='edit_button md-button md-ink-ripple']",
        "select_schedule_date":"//*[@id='input_2']",
        "select_any_date":"//*[@class='md-calendar-date md-calendar-date-today md-focus']",
        "start_time":"//*[@id='scrollDefaultExample']",
        "select_any_time":"((//*[@class='ui-timepicker-list']/..)//ul//li)[1]",
        "enter_days":"//*[@id='activityDurationInput']",
        "enter_seats":"//*[@id='activitySeatsInput']",
        "enter_vanue":"//*[@id='activityVenueInput']",
        "enter_desp_btn":"//*[@id='activityDescriptionInput']",
        "done_btn":"//*[@id='activityCreateButton']",
        "assert_activity":"(//*[text()='Add activity'])[1]",
        "course_name_link":"(//*[@id='content']//a)[11]",
        "course_name_link_wfnen_100":"//*[contains(text(),'Orientation Program in Entrepreneurship (WFNEN 100)')]",
        "click_on_quizes":"//*[@id='assessment']/a",
        "click_on_take_quize":"(//*[@class='button_quiz_assessment'])[1]",    # here index is 1 to 9
        "ques_1":"(//*[@class='form-item'])[5]",                              # here index is 1 to 9
        "submit_ques":"//*[@id='edit-submit']",
        "ques_radio_btn":"//*[@id='edit-tries-1']",
        "yes_qiuz_btn":"//*[text()='Yes']",
        "assert_quiz_result":"//*[text()='Question Results']",
        "your_score":"//*[@id='quiz_score_possible']",
        "view_results":"(//*[contains(text(),'View Result')])[1]",                    # here index is 1 to 9
        "assert_score":"(//*[text()='Score'])[2]",
        "view_solution_btn":"(//*[contains(text(),'Show Solution')])[1]",
        "assert_feedback_video":"//*[text()='Feedback']",
        "close_video":"//*[@class='pp_close']",
        "current_date":"(//*[@id='content']/div[1]/div/table[2]/tbody/tr/td)[2]",
        "view_current_date":"//*[@class='odd'][1]//td[2]",
        "click_on_take_quize_btn":"//*[@class='button_quiz_assessment']",
        "click_on_take_quize_1":"(//*[@class='button_quiz_assessment'])[1]",
        "click_on_take_quize_2":"(//*[@class='button_quiz_assessment'])[2]",
        "click_on_take_quize_3":"(//*[@class='button_quiz_assessment'])[3]",
        "click_on_take_quize_4":"(//*[@class='button_quiz_assessment'])[4]",
        "click_on_take_quize_5":"(//*[@class='button_quiz_assessment'])[5]",
        "click_on_take_quize_6":"(//*[@class='button_quiz_assessment'])[6]",
        "click_on_take_quize_7":"(//*[@class='button_quiz_assessment'])[7]",
        "click_on_take_quize_8":"(//*[@class='button_quiz_assessment'])[8]",
        "click_on_take_quize_9":"(//*[@class='button_quiz_assessment'])[9]",
        "final_assesment_btn":"//*[contains(text(),'FINAL ASSESSMENT ')]",
        "assert_your_score":"//*[text()='Not quite there!']",
        "previous_cycle_text":"//*[@class='label']",
        "updated_cycle_text":"//*[@class='label']",
        "navigate_home_page":"//*[@src='/sites/staging.lms.learnwise.org/learnwise_logo.svg']",
        "click_on_start_course":"(//*[contains(text(),'START COURSE')])",
        "click_on_ok":"(//*[contains(text(),'Ok')])[2]",
        "assert_intro_lesson":"(//*[contains(text(),'Video: Introduction')])[1]",
        "batch_change_dropdown":"//*[@id='user-batch-switch']",
        "assert_preparation_mode":"//*[text()='Preparation mode']",
        "click_on_course_info":"//*[text()='Course info']",
        "assert_course_info":"//*[text()=' About Course ']",
        "assert_tk_qz_time_left":"Time Left : ",
        "student_registration": "//span[text()='STUDENT REGISTRATION']",
        "courses_icon": "//div[@class='tag_title']",
        "MCQ": "//div[contains(text(),'Question')]",
        "click_on_faculty_notes":"//*[text()='Faculty Notes']",
        "assert_faculty_notes":"(//*[contains(text(),'Resources:')])[1]",
        "click_on_course_plan":"(//*[contains(text(),'COURSE PLAN')])[1]",
        "assert_course_plan":"//*[contains(text(),'Course Plan')]",
        "assert_resumen_text":"(//*[contains(text(),'Resumen')])[3]",
        "click_on_mark_as_completed":"(//*[text()='Mark as Completed'])",
        "mark_no_btn":"//*[text()='NO']",
        "star_rating_for_course_plan":"(//*[@ng-repeat='star in stars'])[10]",
        "enter_comment_for_mark":"//*[@class='ng-pristine ng-valid md-input ng-empty ng-touched']",
        "star_mark_submit_btn":"//*[text()='SUBMIT']",
        "assert_active_batches":"//*[text()='Active Batches']",
        "delete_batch_icon":"(//*[@class='fa fa-trash align_right flex-55'])[3]",
        "click_on_delete_batch_tab":"//*[contains(text(),'DELETED BATCHES')]",
        "cilck_on_restore_batch_btn":"(//*[contains(text(),'RESTORE THE BATCH')])", # you can chaned according to batches INDEX 1 to
        "assert_manage_students":"//*[contains(text(),'Manage Students')]",
        "block_btn":"(//*[contains(text(),'BLOCK')])",
        "assert_unblock_btn":"(//*[contains(text(),'UNBLOCK')])[1]",
        "edit_link":"(//*[contains(text(),'EDIT')])",
        "enter_edit_text":"(//*[@name='studentName'])[2]",
        "assert_edit_text":"(//*[@class='profile_name ng-binding ng-scope'])[1]",
        "delete_manage_students":"(//*[text()='DELETE'])",
        "release_tab_text":"(//*[text()='RELEASE'])[1]",
        "closed_batches_button":"//*[contains(text(),'CLOSED BATCHES')]",
        "reopen_the_batches":"(//*[contains(text(),'REOPEN THE BATCH')])",
        "active_batches_reopend":"//*[@class='active_batch_header ng-binding']",
        "schedule_event_btn":"//*[text()='Schedule this event']",
        "edit_ecell_info":"//*[@class='fa fa-pencil ng-scope']",
        "enter_edit_name":"//*[@name='name']",
        "click_on_save":"//*[text()='Save']",
        "assert_name_text":"(//*[@class='ng-binding'])[5]",
        "edit_ceo_button":"//*[text()='EDIT CEO']",
        "select_ceo_search":"//*[@name='studentName']",
        "select_any_one_ceo":"(//*[@class='student_details'])[1]",
        "click_on_update":"//*[text()='UPDATE']",
        "click_to_edit_photos":"(//*[@ng-if='editProfiles'])[2]",
        "click_on_done_btn":"//*[text()='DONE']",
        "completed_activities":"//*[text()='Completed Activities']",
        "assert_practicum":"//*[text()='BASIC']",
        "veiw_pdf_file":"(//*[text()=' VIEW '])[1]",
        "download_pdf_file":"(//*[@class='grey_download_button'])[1]",
        "click_on_practicum_basic":"//*[text()='BASIC']|//*[text()='Basic']",
        "practicum_advanced": "//span[text()='ADVANCED']",
        "click_advanced_file": "//span[text()='09_Lights_Camera_Entrepreneur']",
        "assert_pdf_view":"//*[text()='PDF details']",
        "search_pdf_file":"//*[@ng-model='search.text']",
        "assert_pdf_name":"(//*[@class='file_name layout-xs-row layout-sm-row flex-xs-100 flex-sm-100 flex-50'])[1]",
        "click_on_search_icon":"//*[@ng-click='searchFile()']",
        "assert_learnwise_platform":"(//*[contains(text(),'LearnWISE Platform')])[2]",
        "assert_logout_button":"//*[text()='WELCOME']",
        "copy_batch_details":"(//*[contains(text(),'COPY BATCH')])[1]",
        "assert_green_tick":"//*[contains(@class,'right_icon show')]",
        "profile_icon":"(//*[contains(text(),'Profile')])[1]|//*[text()=' Profile']",
        "assert_profile":"//*[@class='title_text ng-scope']",
        "assert_disabled_next":"//*[@disabled='disabled']",
        "error_message":"//*[@class='growl-message ng-binding']",
        "dashboard_batches":"//*[@class='faculty_course_title']",
        "click_on_wfnen_101_course":"//*[text()='Basic Program in Entrepreneurship (WFNEN 101)']",
        "click on wfnen 102 course":"//div[text()='Intermediate Program in Entrepreneurship (WFNEN 102)']",
        "preview_course": "//div[@class='start_course_button preview']",
        "preview_course_of_101":"//*[text()='Basic Program in Entrepreneurship (WFNEN 101)']/../../..//*[@class='start_course_button preview']",
        "list_of_lesson":"//*[@class=' hide_label  subject_course_title ']",
        "create_batch_in_100":"//*[text()='Orientation Program in Entrepreneurship (WFNEN 100)']/../../..//*[@class='course_create_batch']",
        "batch_created_text":"(//*[@class='col-md-3 batch_card_text ng-binding'])[1]",
        "assert_copy_batch":"//*[text()='Create Batch']",
        "create_batch_in_101":"//*[text()='Basic Program in Entrepreneurship (WFNEN 101)']/../../..//*[@class='course_create_batch']",
        "click_on_copy_batch_101":"//*[text()='Basic Program in Entrepreneurship (WFNEN 101)']/../../..//*[@class='copy_batch_details']",
        "assert_copy_batch_list":"(//*[@ng-repeat='batch in batches | filter:search:strict'])",
        "click_on_create_new_batch_101":"//*[text()='Basic Program in Entrepreneurship (WFNEN 101)']/../../..//*[@class='create_new_batch']",
        "click_on_any_lesson":"//*[@class=' hide_label  subject_course_title ']",
        "assert_full_screen":"//*[@class='show_full_pdf content_is_fullscreen']",
        "assert_normal_screen":"//*[@class='show_full_pdf']",
        "assert_time_left":"//*[text()='Time Left : ']",
        "take_quize_invisible":"//*[contains(text(),'Lesson 1: Let')]/following-sibling::*//*[contains(text(),'Take Quiz')]",
        "take_quize_3_times_lesson_5":"//*[contains(text(),'Lesson 5:')]/following-sibling::*//*[@class='button_quiz_assessment']",
        "view_results_lesson_5":"//*[contains(text(),'Lesson 5:')]/following-sibling::*//*[@class='quiz_take_button']",
        "take_quize_3_times_lesson_2":"//*[contains(text(),'Lesson 2:')]/following-sibling::*//*[@class='button_quiz_assessment']",
        "final_assesment_enable_btn":"(//*[@class='faculty_final_assessment_button final_assessment_button_enabled'])[1]",
        "course_plan_lessons":"//*[contains(text(),' Lesson')]",
        "Mark_as_complete": "//span[text()='Mark as Completed']",
        "select_date_for_lesson_1":"//*[contains(text(),' Lesson 1')]/../../..//*[@class='md-datepicker-input']",
        "click_on_mark_as_completed_lesson_5":"//*[contains(text(),' Lesson 5')]/../../../../following-sibling::div//*[text()='Mark as Completed']",
        "star_rating_mark_as_completed":"(//*[text()='Tell us how we are doing.']/../following-sibling::div//li)[5]",
        "feedback_submit_rating_lesson_5":"//*[contains(text(),' Lesson 5')]/../../../../following-sibling::div//*[@class='feedback_star ng-isolate-scope']",
        "assert_current_date":"(//*[@class='md-calendar-date-selection-indicator'])",
        "click_on_play_vdo_welcome":"(//*[@class='single_content_image_play'])[1]",
        "assert_manage_batches":"//*[@ng-repeat='batch in batches.activeBatches']",
        "edit_batch_details_icon":"//*[@ui-sref='editBatch({batchId:batch.id})']",
        "edit_icon1": "//i[@flex='45']",
        "edit_icon": "//i[@class='fa fa-pencil align_right click_able flex-45']",
        "edit_batches":"//span[text()='EDIT']",
        "edit_batches1": "//div[@class='col-md-3 batch_card_text ng-binding']",
        "enter_batch_name": "//*[@name='batchName']",
        "assert_chat_message":"//*[@class='chat_message ng-binding']",
        "chat_message_icon":"//*[text()=' Chat']",
        "type_chat_message":"//*[@ng-model='chat.message']",
        "send_chat_message":"//*[text()='send']",
        "click_on_no_upcoming_module":"//*[text()='No Upcoming Module']",
        "click_on_manage_students":"//*[text()='Manage Students']",
        "enter_student_name":"//*[@name='studentName']",
        "click_on_green_tick":"//*[@ng-click='sendStudentDetails(studentData)']",
        "assert_student_name":"//*[@class='profile_name ng-binding ng-scope']",
        "click_on_release_tab":"//*[text()='RELEASE']",
        "click_on__edit_green_tick":"//*[@ng-click='updateStudentDetails(student)']",
        "observe_num_of_students":"//*[@class='Student_detail_text ng-binding']",
        "run_lesson_tab":"//*[text()='RUN LESSON']",
        "click_on_close_batch_tab":"//*[text()='CLOSE BATCH']",
        "rating_for_closed_batches":"(//*[text()='Please take a minute to rate']/..//li)[5]",
        "search_copy_batch":"//*[@placeholder='Search']",
        "copy_batch_search_icon":"//*[@class='fa fa-search search_action']",
        "time_activities":"//*[@name='time']",
        "select_time_schedule":"(//*[@class='ui-timepicker-pm'])[19]",
        #"select_time_schedule":"(//*[@class='ui-timepicker-wrapper']//li)",
        "assert_done_activities":"//*[text()='Activity created successfully!']",
        "assert_cover_pic":"//*[text()='E-Cell updated successfully!']",
        "date_for_past": "//*[@aria-label='Friday March 2 2018']",
        "date_for_future": "//td[@aria-label='Monday April 30 2018']",
        "save_ad_draft":"//*[@aria-label='SAVE_AS_DRAFT']",
        "assert_activities_draft":"//*[text()='Activity drafted successfully!']",
        "click_on_draft":"(//*[text()='Drafts'])[1]",
        "assert_draft_activities":"//*[@ng-repeat='activity in draftsActivities']",
        "assert_invite_only_text":"//*[text()='Activity created successfully!']",
        "team_members":"//*[@class='eleader_list md-no-proxy ng-scope _md']",
        "practicum_contents":"//*[@ng-repeat='folder in rootFolders']",
        "click_on_practicum":"//*[text()='PRACTICUM']",
        "search_pdf_details":"//*[@ng-repeat='file in files']",
        "user_guide_tab":"(//*[text()='User Guide'])[2]",
        "feedback_title":"(//*[@type='text'])[2]",
        "feedback_next_btn":"(//*[@value='Next'])[1]",
        "feedback_contact":"(//*[@class='UR_element '])[1]",
        "feedback_supports":"//*[text()='Feedback & Support']",
        "feedback_description":"(//*[@placeholder='Description'])[3]",
        "feedback_email":"(//*[@ur-element='email'])[2]",
        "feedback_name":"(//*[@ur-element='name'])[2]",
        "feedback_submit":"(//*[@ur-element='submit'])[6]",
        "skip_and_create":"(//*[contains(text(),'Skip and Create')])[5]",
        "edit_profile_account":"//*[@href='#/IN/en/faculty/profile/edit']",
        "edit_first_name":"//*[@name='firstName']",
        "edit_last_name":"//*[@name='lastName']",
        "save_changes":"//*[text()='SAVE CHANGES']",
        "assert_save_changes":"//*[contains(@class,'profile_name col-md')]",
        "profile_updated":"//*[text()='Profile updated successfully!']",
        "feedback_and_supports":"//*[text()='Feedback & Support']",

# wadhwani_student_xpath

        "join_batch_btn":"//*[text()='JOIN']",
        "click_on_batch_name": "//*[@class='batch_name click ng-binding']",
        "assert_enrolled_course": "(//*[@class='nav-link ng-binding'])[2]",
        "student_course_header":"//*[@id='mysubs-menu']/a|//*[@id='student_courses']",
        "assert_intro_vdo":"//*[@class='chapter_title']",
        "assert_quize_lesson":"//*[@id='task_title_assessment']",
        "quiz_header_tab": "//a[text()='Quizzes']",
        "assert_quize_page":"(//*[text()='Quizzes'])[2]",
        "view_3_times_results":"(//*[text()='View Result'])",
        "list_course_info":"//*[@id='about_tab_content']//p",
        "click_on_leave_batch":"((//*[text()='LEAVE BATCH']))[2]",
        "assert_recent_activities":"//*[@class='faculty_activities_wrapper']",
        "edit_ecell_profile":"(//*[@ng-if='editProfiles'])[3]",
        "assert_withdraw_btn":"(//*[text()=' WITHDRAW '])[1]",
        "click_on_activity":"//*[text()='Activity']",
        "click_on_any_events":"(//*[@ng-click='activityDetail(upcomingActivity)'])", # here you need to change according to how many activities are there
        "click_on_ongoing_activities":"//*[text()='Ongoing Activities']",
        "click_on_any_activities":"(//*[@ng-click='activityDetail(ongoingActivity)'])[1]",
        "assert_go_live":"//*[contains(text(),' GO LIVE!')]",
        "assert_publish_draft":"(//*[text()='Publish'])",
        "check_edit_activities":"//*[text()='Edit activity']",
        "give_stars_rating":"(//*[@ng-repeat='star in stars'])[5]",
        "assert_invite_only":"//*[@id='activityInviteOnly']",
        "assert_i_am_live":"//*[@ng-click='activityAction(activity,$event)']",
        "click_on_team":"//*[text()='TEAM']",
        "assert_team_list":"//*[@class='eleader_list md-no-proxy ng-scope _md']",
        "click_on_leader":"//*[text()='Add leader']",
        "select_role":"(//*[@name='role'])[1]",
        "select_any_one_role":"(//*[@ng-repeat='role in roles'])[3]",
        "select_a_student":"//*[@type='search']",
        "select_any_one_student":"(//*[@class='item-title'])[2]",
        "list_of_available_batches":"//*[contains(text(),'Available')]",
        "assert_student_dashboard":"//*[text()='Your courses will appear once they are created. You can use dashboard to track the progress of each of your courses. Please navigate to ']",
        "student_dashboard_header":"//*[@id='student_dashboard']|//*[@id='home']/a",
        "final_assesment_disable_btn":"(//*[@class='faculty_final_assessment_button final_assessment_button_disabled'])[1]",
        "prev_vdo_text":"(//*[contains(text(),'Video: Introduction')])[3]",
        "next_vdo_text":"(//*[contains(text(),'Video: Welcome ')])[2]",
        "click_on_edit_cover_photos":"//*[@ng-model='selected.cover']",
        "select_any_upcoming_activities":"(//*[@ng-click='activityDetail(upcomingActivity)'])",
        "click_on_attend_btn":"//*[contains(text(),'ATTEND')]",
        "click_on_withdraw_btn":"//*[contains(text(),' WITHDRAW ')]",
        "select_any_ongoing_activities":"(//*[@ng-click='activityDetail(ongoingActivity)'])",
        "select_any_completed_activities":"",
        "submitted_successfully":"//*[text()='Submitted successfully!']",
        "assert_published_activities":"//*[text()='Activity published successfully!']",
        "assert_eleader_activities":"//*[text()='E-leader added successfully.']",
        "click_on_student_eleader":"(//*[@ui-sref='ecellMemberDetail({ecellId:ecellId, memberId:user.id})'])[3]",
        "remove_from_ecell":"//*[@ng-click='confirmationDialog($event, memberDetails)']",
        "assert_removed_ecell":"//*[text()='User removed from E-Cell successfully!']",
        "click_on_subfolder_of_basic":"//*[contains(@ng-repeat,'folder in subfolders |  or')]",
        "click_on_student_batch_chat":"//*[text()='Chat']",
        "click_on_student_number":"//*[@class='click_able ng-binding ng-scope']",
        "click_on_student_name":"//*[@class='click_able ng-binding']",
        "assert_student_details":"//*[text()='Student Details']",
        "assert_participates":"//*[text()='Participants']",
        "student_profile_icon":"(//*[text()='Profile'])[2]",
        "student_edit_icon":"(//*[@class='click_able'])[2]",


    },
    "id":{
        "button": "buttonId",
        "password": "password",

    },
    "name":{
        "by_name": "name",
        "roles": "role",
    },

    "linkText": {
        "value": "Course info"
    },

    "css_selector":{

        "feedback_contacts":"#ur_desktop_main_supportCenter_6 > div.UR_element.UR_contentFull > div > div.UR_element.UR_formToggle.\31 > label:nth-child(2)",
        "take_quize_5_btn":"#content > div.content-middle > div > div > div:nth-child(5) > div.quiz_inner_list_wrapper1 > div.quiz_list_button > div > a > div",

    },

    "class_name":{
        "checkbox": "android.widget.CheckBox"
    }
}
