user_dict={

    "user_data":{

# Faculty_user_data
        "browser_name":"chrome",
        "chrome_driver_path":"C:\\Users\\Lenovo\\Downloads\\Wadhwani_web_python_automation (2)\\Wadhwani_web_python_automation\\main\\requirements\\browser_drivers",
        "url":"https://staging.learnwise.org",
        "faculty_username":"automation1@gmail.com",
        "faculty_password": "pass",
        "test_username":"manju@test.com",
        "assert_video_title_text":"VIDEO: Introducción",
        "assert_video_intro_text":"Video: Introduction",
        "enter_batch_name":"BATCH_1",
        "enter_batch_name_for_101":"BATCH_2",
        "enter_copy_batch":"Copied_batch",
        "enter_num_of_students":"20",
        "assert_batch_data":"Batch Details",
        "assert_teaching_mode_data":"Teaching mode",
        "assert_green_data":"Resumen",
        "recent_activities_data":"Recent Activities",
        "enter_comment_close_batches":"This batch is closed",
        "assert_congs_text":"Congratulations!",
        "enter_ecell_name":"vikash",
        "enter_website":"www.google.com",
        "enter_description":"Tested",
        "enter_vanue_text":"Bangalore",
        "enter_desp_text":" Testing",
        "enter_days":"2",
        "enter_seats":"15",
        "enter_vanue_sch":"Chennai",
        "enter_desp_btn":" Hello",
        "assert_activity_text":"Add activity",
        "assert_quiz_result":"Question Results",
        "assert_score":"Score",
        "assert_feedback_video":"Feedback",
        "assert_zero_batch":"Active Batches (0)",
        "assert_view_results":"View Results",
        "view_result_asssert":"View Result",
        "assert_your_score":"Not quite there!",
        "assert_cycle_text":"0%",
        "dashboard_text":"DASHBOARD",
        "course_header_text":"COURSES",
        "assert_preview_course":"COURSE DETAILS",
        "assert_manage_batch":"MANAGE BATCHES",
        "copy_batch": "Copy batch",
        "batch_name_copy": "black",
        "search_copy_batch_name":"batch",
        "assert_preparation_mode":"Preparation mode",
        "assert_course_information":"About Course",
        "assert_take_quiz":"Take Quiz",
        "assert_tk_qz_time_left":"Time Left : ",
        "question_no":"Question 1 of 10",
        "email_for_unregistered": "bhavya@gmail.com",
        "student_reg": "STUDENT REGISTRATION",
        "assert_faculty_notes":"Resources:",
        "assert_course_plan":"Course Plan",
        "assert_resumen_text":"Resumen",
        "assert_yes_text":"YES",
        "enter_comment_mark_completed":"Mark has been completed",
        "assert_active_batches_text":"Active Batches",
        "assert_manage_students":"Manage Students",
        "assert_unblock_btn":"UNBLOCK",
        "assert_relese_text":"RELEASE",
        "assert_block_text":"BLOCK",
        "reopen_the_batches":"REOPEN THE BATCH",
        "schedule_event_btn":"SCHEDULE THIS EVENT",
        "enter_edit_name_text":"rani",
        "click_on_update":"UPDATE",
        "assert_practicum":"BASIC",
        "pdf_view_option": "VIEW",
        "pdf_file_name":".pdf",
        "assert_learnwise_platform":"LEARNWISE PLATFORM",
        "assert_logout_text":"WELCOME",
        "search_copy_batch":"BATCH",
        "invalid_email_id":"vn12325467",
        "valid_email_id":"demogoogle@test.com",
        "incorrect_password":"12345",
        "error_message":"These credentials do not match our records.",
        "assert_copy_batch":"CREATE BATCH",
        "assert_activities_draft":"Activity drafted successfully!",
        "assert_invite_only_text":"Activity created successfully!",
        "assert_pdf_view":"PDF details",
        "question":"TESTED",
        "edit_first_name":"Vikash",
        "edit_last_name":"Narayan",
        "profile_updated":"Profile updated successfully!",

# student_user_data

        "student_username":"student2856@gmail.com",
        "student_password":"pass",
        "assert_course_header":"COURSES",
        "assert_course_info":"COURSE INFO",
        "assert_quizes":"Quizzes",
        "join_btn_text":"JOIN",
        "assert_withdraw_btn":"WITHDRAW",
        "assert_go_live":"GO LIVE!",
        "assert_publish_draft":"PUBLISH",
        "assert_i_am_live":"I'M LIVE",
        "assert_add_leader":"ADD LEADER",
        "assert_profile":"Profile",
        "edit_batch_name": "EDITED_BATCH",
        "edit_students_number":"33",
        "type_chat_message":"Hello",
        "enter_student_name":"VIKASH",
        "manage_std_name_edit":"Narayan",
        "assert_done_creativities":"Activity created successfully!",
        "assert_cover_pic":"E-Cell updated successfully!",
        "assert_student_dashboard":"Your courses will appear once they are created. You can use dashboard to track the progress of each of your courses. Please navigate to ",
        "submitted_successfully":"Submitted successfully!",
        "assert_published_activities":"Activity published successfully!",
        "assert_eleader_activities":"E-leader added successfully.",
        "assert_removed_ecell": "User removed from E-Cell successfully!",
        "":"",



    }
 }

